### ISSUE TITLE
Build Stronger Tests

### ISSUE THREAD

**Issue by javenb022** [turing-2303-mod-1-group-project/futbol#37]
- [ ] Initialize each do, expect game to be a Game (each initialize)x3 (add underscore on game teams)
- [ ] All season stats(x6) copy 'it' block for more tests

Helper methods we can't improve. (x10) That we can
- [x] generate_game_ids

**Comment by garrettgregor** [comment]
@javenb022 can you close this issue now?

**Comment by MylesNottingham** [comment]
Ran out of time.
